### ISSUE TITLE
shuffling minibatches

### ISSUE THREAD

**Issue by samkohn** [NERSC/dayabay-learn#6]
Commit 16e081d627c3459923098b911a68f29cd69d13df removes shuffled minibatches. I put that in because in the online course that taught me about NNs, the minibatches were shuffled to increase the "stocastic-ness" of the SGD. But if it's not commonly used/doesn't help, then we should take it out. Did you have a specific reason to change it?

**Comment by eracah** [comment]
No we can put it back in. I did not mean to remove it. I just meant to add in the functionality that iterates minibatches even if the dataset is not a multiple of batch size because it just truncates the last dataset_size % minibatch_size examples. I think its not terribly uncommon, but I am not sure. I think you should keep it in.
